const {chromium}=require("playwright");const fs=require("fs");
(async()=>{const browser=await chromium.launch({channel:"chrome"});const context=await browser.newContext();const page=await context.newPage();page.on("dialog",d=>d.accept());const results=[];const defs=[
{file:"database_generus",svc:"generus",key:"ppg_maksel2_generus_data",name:"name",open:"openModal(\"modalAddGenerus\")",fields:{addName:"AUDIT CRUD",addGender:"L",addBirthDate:"2010-01-01",addCategory:"Remaja",addGroup:"Kelompok A",addVillage:"Barabaraya",addStatus:"Aktif"},create:"handleCreateGenerus",edit:"openEditModal",editField:"editName",update:"handleUpdateGenerus",del:"openDeleteModal(id,\"AUDIT\");await confirmDeleteGenerus()"},
{file:"absensi",svc:"absensi",key:"ppg_maksel2_absensi_data",name:"name",open:"openModal(\"modalAddAbsensi\")",fields:{addName:"AUDIT CRUD",addCategory:"Remaja",addGroup:"Kelompok A",addEvent:"Pengajian Rutin",addDate:"2026-09-10",addTime:"08:00"},create:"handleCreateAbsensi",edit:"openEditModal",editField:"editName",update:"handleUpdateAbsensi",del:"openDeleteModal(id,\"AUDIT\");await confirmDeleteAbsensi()"},
{file:"program_kerja",svc:"proker",key:"proker_data",name:"nama",open:"openTambahModal()",fields:{formNama:"AUDIT CRUD",formPJ:"Petugas Audit",formTanggalMulai:"2026-09-10",formTanggalSelesai:"2026-09-11"},create:"saveProgram",edit:"openEditModal",editField:"formNama",update:"saveProgram",del:"openHapus(id);await confirmHapus()"},
{file:"laporan",svc:"lupg",key:"ppg_laporan_data",name:"catatan",open:"bukaTambahLupg()",fields:{inputKelompokLupg:"Kelompok A",inputBulanLupg:"September",inputTargetLupg:"100",inputTercapaiLupg:"80",inputStatusLupg:"Baik",inputCatatanLupg:"AUDIT CRUD"},create:"simpanLupg",editCode:"bukaDetailLupg(rawData.findIndex(x=>x.id===id));document.getElementById(\"btnEditLupg\").click()",editField:"inputCatatanLupg",update:"simpanLupg",del:"bukaDetailLupg(rawData.findIndex(x=>x.id===id));await document.getElementById(\"btnHapusLupg\").onclick()"},
{file:"dokumentasi",svc:"dokumentasi",key:"ppg_dokumentasi_data",name:"judul",open:"bukaTambahDok()",fields:{inputJudulDok:"AUDIT CRUD",inputTanggalDok:"2026-09-10",inputKategoriDok:"Kajian",inputLokasiDok:"Maksel 2",inputJumlahFotoDok:"1",inputUrlDok:"https://example.com/audit.png"},create:"simpanDokumentasi",editCode:"editDokumentasi(currentDokList.find(x=>x.id===id))",editField:"inputJudulDok",update:"simpanDokumentasi",del:"bukaDetailDok(id);await document.getElementById(\"btnHapusDok\").onclick()"},
{file:"arsip",svc:"arsip",key:"ppg_arsip_data",name:"nama",open:"bukaUploadArsip()",fields:{inputNamaArsip:"AUDIT CRUD",inputKategoriArsip:"Laporan LUPG",inputTanggalArsip:"2026-09-10",inputTipeArsip:"PDF"},create:"unggahDokumen",edit:"editArsip",editField:"inputNamaArsip",update:"unggahDokumen",del:"await hapusArsip(id,\"AUDIT\")",upload:true}
];
for(const d of defs){const r={file:d.file};try{await page.goto(`http://127.0.0.1:4173/${d.file}.html`,{waitUntil:"load"});await page.waitForTimeout(400);await page.evaluate(d=>{eval(d.open);for(const [id,v]of Object.entries(d.fields))document.getElementById(id).value=v;},d);if(d.upload)await page.locator("#inputFileArsip").setInputFiles({name:"audit.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4 audit")});await page.evaluate(async d=>{await window[d.create]({preventDefault(){},target:{reset(){}}});},d);let rows=await page.evaluate(d=>PPG_DB[d.svc].list(),d);let item=rows.find(x=>x[d.name]==="AUDIT CRUD");if(!item)throw Error("Create missing");r.create=true;const id=item.id;await page.reload({waitUntil:"load"});await page.waitForTimeout(200);r.reload=await page.evaluate(({d,id})=>PPG_DB[d.svc].list().then(rows=>rows.some(x=>x.id===id)),{d,id});await page.evaluate(async({d,id})=>{if(d.editCode)eval(d.editCode);else window[d.edit](id);document.getElementById(d.editField).value="AUDIT UPDATED";await window[d.update]({preventDefault(){},target:{reset(){}}});},{d,id});r.update=await page.evaluate(({d,id})=>PPG_DB[d.svc].list().then(rows=>rows.some(x=>x.id===id&&x[d.name]==="AUDIT UPDATED")),{d,id});await page.evaluate(async({d,id})=>{await eval(`(async()=>{${d.del}})()`);},{d,id});r.delete=await page.evaluate(({d,id})=>PPG_DB[d.svc].list().then(rows=>!rows.some(x=>x.id===id)),{d,id});await page.evaluate(d=>localStorage.setItem(d.key,"[]"),d);await page.reload({waitUntil:"load"});await page.waitForTimeout(200);r.emptyPersists=await page.evaluate(d=>PPG_DB[d.svc].list().then(rows=>rows.length===0),d);}catch(e){r.error=e.message;}results.push(r);console.log(r);}
await page.goto("http://127.0.0.1:4173/pengaturan.html");results.push({file:"pengaturan",result:await page.evaluate(async()=>{document.getElementById("orgName").value="AUDIT ORG";await saveOrganization();return (await PPG_DB.pengaturan.list())[0]?.nama_organisasi==="AUDIT ORG";})});fs.writeFileSync("/tmp/ppg-ui-audit/crud-results.json",JSON.stringify(results,null,2));await browser.close();})();
